
2020-03-19 23:41:11,812 INFO: errors [in app.py:507]
2020-03-19 23:41:31,473 INFO: errors [in /home/lyon/Documents/udacity/FSND/projects/01_fyyur/starter_code/app.py:507]
2020-03-19 23:43:32,280 INFO: errors [in app.py:508]
2020-03-19 23:43:35,417 INFO: errors [in /home/lyon/Documents/udacity/FSND/projects/01_fyyur/starter_code/app.py:508]
2020-03-19 23:44:25,599 INFO: errors [in /home/lyon/Documents/udacity/FSND/projects/01_fyyur/starter_code/app.py:510]
2020-03-19 23:44:44,106 INFO: errors [in /home/lyon/Documents/udacity/FSND/projects/01_fyyur/starter_code/app.py:510]
2020-03-21 21:37:41,835 INFO: errors [in app.py:510]
2020-03-21 21:37:57,512 ERROR: Exception on /shows/create [GET] [in /home/lyon/.local/lib/python3.5/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 478, in create_shows
    form = ShowForm()
  File "/home/lyon/.local/lib/python3.5/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/lyon/.local/lib/python3.5/site-packages/wtforms/form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/lyon/.local/lib/python3.5/site-packages/wtforms/form.py", line 132, in process
    field.process(formdata)
  File "/home/lyon/.local/lib/python3.5/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/csrf.py", line 141, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/csrf.py", line 35, in generate_csrf
    message='A secret key is required to use CSRF.'
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-03-21 21:49:19,700 ERROR: Exception on /venues/create [GET] [in /home/lyon/.local/lib/python3.5/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 220, in create_venue_form
    form = VenueForm()
  File "/home/lyon/.local/lib/python3.5/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/lyon/.local/lib/python3.5/site-packages/wtforms/form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/lyon/.local/lib/python3.5/site-packages/wtforms/form.py", line 132, in process
    field.process(formdata)
  File "/home/lyon/.local/lib/python3.5/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/csrf.py", line 141, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/csrf.py", line 35, in generate_csrf
    message='A secret key is required to use CSRF.'
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-03-21 21:52:03,955 ERROR: Exception on /artists/create [GET] [in /home/lyon/.local/lib/python3.5/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 413, in create_artist_form
    form = ArtistForm()
  File "/home/lyon/.local/lib/python3.5/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/lyon/.local/lib/python3.5/site-packages/wtforms/form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/lyon/.local/lib/python3.5/site-packages/wtforms/form.py", line 132, in process
    field.process(formdata)
  File "/home/lyon/.local/lib/python3.5/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/csrf.py", line 141, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/csrf.py", line 35, in generate_csrf
    message='A secret key is required to use CSRF.'
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-03-21 21:52:06,406 ERROR: Exception on /venues/create [GET] [in /home/lyon/.local/lib/python3.5/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 220, in create_venue_form
    form = VenueForm()
  File "/home/lyon/.local/lib/python3.5/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/lyon/.local/lib/python3.5/site-packages/wtforms/form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/lyon/.local/lib/python3.5/site-packages/wtforms/form.py", line 132, in process
    field.process(formdata)
  File "/home/lyon/.local/lib/python3.5/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/csrf.py", line 141, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/csrf.py", line 35, in generate_csrf
    message='A secret key is required to use CSRF.'
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-03-21 21:52:26,605 ERROR: Exception on /shows/create [GET] [in /home/lyon/.local/lib/python3.5/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyon/.local/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 478, in create_shows
    form = ShowForm()
  File "/home/lyon/.local/lib/python3.5/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/lyon/.local/lib/python3.5/site-packages/wtforms/form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/lyon/.local/lib/python3.5/site-packages/wtforms/form.py", line 132, in process
    field.process(formdata)
  File "/home/lyon/.local/lib/python3.5/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/csrf.py", line 141, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/csrf.py", line 35, in generate_csrf
    message='A secret key is required to use CSRF.'
  File "/home/lyon/.local/lib/python3.5/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-03-21 22:36:00,468 INFO: errors [in /home/lyon/Documents/udacity/FSND/projects/01_fyyur/starter_code/app.py:517]
2020-03-21 22:36:34,987 INFO: errors [in /home/lyon/Documents/udacity/FSND/projects/01_fyyur/starter_code/app.py:517]
2020-03-21 22:36:39,643 INFO: errors [in /home/lyon/Documents/udacity/FSND/projects/01_fyyur/starter_code/app.py:517]
